#!/bin/bash

# DNS Configuration (systemd-resolved)
echo "Configuring DNS..."
DNS_SERVERS=(
    "8.8.8.8"  # Google Public DNS
    "8.8.4.4"  # Google Public DNS
    "1.1.1.1"  # Cloudflare DNS
    "1.0.0.1"  # Cloudflare DNS
    "10.202.10.202" #https://dns.403.online/dns-query
    "10.202.10.102" #dns.403.online
)

RESOLV_CONF="/etc/resolv.conf"
echo "# Generated by configuration script" > "$RESOLV_CONF"
for DNS in "${DNS_SERVERS[@]}"; do
    echo "nameserver $DNS" >> "$RESOLV_CONF"
done

sudo systemctl restart systemd-resolved
echo "DNS configuration complete."

# Firewall Configuration (firewalld)
echo "Configuring firewall (firewalld)..."
SERVICES_TO_ALLOW=("http" "https" "ssh")
PORTS_TO_ALLOW=("22/tcp 9011/tcp")

for SERVICE in "${SERVICES_TO_ALLOW[@]}"; do
    sudo firewall-cmd --permanent --add-service="$SERVICE"
done

for PORT in "${PORTS_TO_ALLOW[@]}"; do
    sudo firewall-cmd --permanent --add-port="$PORT"
done

sudo firewall-cmd --reload
echo "Firewall configuration complete."

echo "Initial configuration finished!"
echo "Please reboot the system to apply all changes."
firewall-cmd --permanent --add-port=80/tcp 8080/tcp 9011/tcp 443/tcp 22/tcp